# Generated by Django 4.0.5 on 2022-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='given_name',
            field=models.CharField(default='kate', max_length=255),
            preserve_default=False,
        ),
    ]
